### PR TITLE
Amir

### PR DESCRIPTION
**Pull request by ayunas**
@RaineBeauDubs

set up the LS8 to run the print8.ls8 program.

### CODE REVIEW

**Comment by ayunas** [comment]
@RaineBeauDubs 

the LS8 CPU constructor can handle all ls8 assembly language files in the examples directory, which was implemented yesterday. 

the mult.ls8 runs correctly in the ls8.py file.  implemented the multiplication instruction (opcode)

**Comment by ayunas** [comment]
@RaineBeauDubs 

set up the push and pop instructions which add values to a chunk of ram designated for the stack.  
ls8.py can run the stack.ls8 assembly code successfully with output of 2 4 1

**Comment by ayunas** [comment]
@RaineBeauDubs 
Subroutines implemented with the CALL AND RET INSTRUCTIONS.  call.ls8 executes correctly

**Comment by ayunas** [comment]
finished setting up ST instruction. 
@RaineBeauDubs

**Review by RaineBeauDubs — APPROVED** [review]

**Pull request merged**
